name: spell_champ_frontend
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0
  

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  provider: 6.1.4
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.4
  logger: ^2.0.2
  flutter_tts: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/grade_1.png
    - assets/images/grade_2.png
    - assets/images/grade_3.png
    - assets/images/grade_4.png
    - assets/images/grade_5.png
    - assets/images/grade_6.png
    - assets/images/grade_7.png
    - assets/images/grade_8.png
    - assets/images/grade_9.png
    - assets/images/grade_10.png
    - assets/images/grade_11.png
    - assets/images/grade_12.png
    - assets/images/spell-champ-logo.png   
    - assets/images/diamond.png 
    - assets/images/next.png
    - assets/images/volume.png

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/YoungSerif-Regular.ttf
          weight: 900
        


  